title:              Sol's Blog
email:              dsolkim1030@gmail.com
description:        This is the decription of the blog
author:             Sol
# baseurl:            ""
url:                "https://soulfulsol.github.io"

# Social Profiles
twitter_username:   
github_username:    SoulfulSol
facebook_username:  facebook
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
